FFXIV-CombatReborn/RebornRotations

- BasicRotations/Melee/RPR_Default.cs
- BasicRotations/RebornRotations.csproj
> DT RPR Cleanup

- BasicRotations/Tank/PLD_Default.cs
looks like there's still some issue with Confiteor but i don't know which Base change would fix it, in the mean time that appears to work that way
> updated with Blade Combo + Supplication + Sepulchre

- BasicRotations/Tank/PLD_Default.cs
> FoF Requiescat change keeping the old one commented

- BasicRotations/Tank/GNB_Default.cs
> Fix DD on GNB

- BasicRotations/Magical/SMN_Archive
- BasicRotations/Magical/SMN_Default.cs
additionally added old SMN rotation as an archive
> ICWA SMN added to RebornRotations, now new default

- BasicRotations/Magical/RDM_Default.cs
Added 100 abilities
fixed mana for moulinet
reprise while moving
> Rdm lvl 100 support

- .gitignore
- BasicRotations/Magical/PCT_Default.cs
- BasicRotations/Melee/NIN_Default.cs
- BasicRotations/RebornRotations.csproj
PCT Rotation tried some sketchy boolean checks to have Starry Muse not casted if MogoftheAges can be used
> PCT Rotation 80

- BasicRotations/Tank/WAR_Default.cs
DefenseSingleAbility should return base.DefenseSingleAbility
> WAR: fixed typo in return of DefenseSingle

- BasicRotations/Melee/SAM_Default.cs
> Updated using of smn job

- BasicRotations/Melee/SAM_Default.cs
Based on the RSR SAM spell updates, merged two version of RR SAM rotation files. Delayed opener for manually weaving tincture + correct level 100 spells. Single target and AOE are tested on dummy and level 70 and 100 dungeons (both synced, but not full clear).
> Merge SAM changes

- BasicRotations/Melee/MNK_Default.cs
This should work at lower levels now. I haven't checked everything, but seemed functional at lv 15 and 80.
> Added logic for 3 actions so usable at lower levels - Monk Rotation

- BasicRotations/Healer/SGE_Default.cs
- Added the Psyche attack ability, no logic.
- Added Eukrasian Prognosis II. #60 
- Fixed a problem where Pneuma would be fired if any party member is dead.
> Sage fixes

- BasicRotations/Tank/GNB_Default.cs
TODO: CHECK WHY SKIP COMBO NEEDS TO BE THERE
> Fixed Reign Combo

- BasicRotations/Tank/GNB_Default.cs
- Fixed Reign inconsistency
- Fixed DangerZone/BlastZone for all levels
- Fixed BowShock for all levels
- Balance Opener 2.50GCD
- Balance Burst Without No Bloodfest 2.50GCD
- Balance Burst With  Bloodfest 2.50GCD
> Dickbreaker

- BasicRotations/Healer/SGE_Default.cs
- BasicRotations/RebornRotations.csproj
First pass at SGE DT support, tested in duty support. Also nuget bump
> First pass at SGE DT support, tested in duty support. Also nuget bump

- BasicRotations/Melee/RPR_Default.cs
2:57 in the Level 100 Stone, Sky, Sea
https://www.fflogs.com/reports/a:6dz1cmrMGyhL9FjX#fight=1
https://i.imgur.com/35RS9bV.png
> Prioritize Perfectio so it fits into Arcane Circle window

- BasicRotations/Healer/AST_Default.cs
- BasicRotations/Melee/VPR_Default.cs
- BasicRotations/RebornRotations.csproj
AST: fixed some miscatigorized and misordered heals and mits
VPR: Fix AOE combo
> AST and VPR hotfix

- BasicRotations/Ranged/MCH_Default.cs
Tidy up the code and comments in CountDownAction and GeneralGCD. Removed obviously redundant logical checks. Other parts for further investigation are marked. Tested on level 100 stone, sky, sea synced for single target and Lapis Manalis (level 90 support) for aoe.
> Tidy up CountDownAction and GeneralGCD

- BasicRotations/Tank/zPLD_Alpha.cs
Significantly improved redundancy with better logic. Improved Priority of oGCDs. Better Downtime recovery.
> Improved Logic for zPLD_Alpha.cs

- BasicRotations/Healer/SCH_Default.cs
- BasicRotations/Healer/SGE_Default.cs
- BasicRotations/Melee/DRG_Default.cs
- BasicRotations/Ranged/BRD_Default.cs
- BasicRotations/RebornRotations.csproj
- BasicRotations/Tank/DRK_Default.cs
DRK- Delirium Combo and Disesteem fixed
DRG- Buff alignment fix, Battle Litany will now only be used if you already have Lance Charge buff, and lance charge will hold its use to sync with battle litany
SCH- Countdown action fix attempt
SGE- Countdown Dosis timing fix
> Various fixes

- BasicRotations/Healer/SCH_Default.cs
- BasicRotations/Magical/ICWA_PCT_BETA.cs
- BasicRotations/Magical/PCT_Default.cs
- BasicRotations/Magical/SMN_Default.cs
- BasicRotations/Melee/MNK_Default.cs
- BasicRotations/Melee/NIN_Default.cs
- BasicRotations/Melee/SAM_Default.cs
- BasicRotations/Ranged/BRD_Default.cs
Added `Config Options` and `Countdown logic` regions to `ICWA_PCT_BETA.cs` and `PCT_Default.cs`. Updated `EmergencyAbility` in `SMN_Default.cs` and added `GCD Logic` region. Removed `Extra Methods` region from `MNK_Default.cs`, `NIN_Default.cs`, and `SAM_Default.cs`. Improved formatting in `BRD_Default.cs`.
> Add config options, update methods, and clean up code

- BasicRotations/Healer/SGE_Default.cs
- BasicRotations/RebornRotations.csproj
Modified SGE_Default to conditionally turn off Eukrasia status effect based on combat status and target condition. Updated RebornRotations.csproj to use RotationSolverReborn.Basic version 7.0.5.74.
> Add conditional status effect handling and update package

- BasicRotations/Melee/SAM_Default.cs
- Now refreshes higanbana if it is available and the DOT timer is 18 seconds or less
- Starts with applying Dmg and Haste buff first before doing Yukikaze combo
> Sam Adjustments

- BasicRotations/Melee/SAM_Default.cs
Some people were saying that SAM isn't using Zanshin before Senei so i moved it up in priority
> Zanshin priority

- BasicRotations/Healer/AST_Default.cs
- BasicRotations/RebornRotations.csproj
Updated AST_Default.cs with new config options LightspeedMove and SmartCard, and adjusted logic in CountDownAction and AttackAbility methods. Modified conditions for TheBalancePvE, TheSpearPvE, and LordOfCrownsPvE abilities. Added logic for LightspeedPvE usage. Updated RebornRotations.csproj to reference RotationSolverReborn.Basic package version 7.0.5.114.
> Add new config options and update logic in AST_Default

- BasicRotations/Melee/VPR_Default.cs
Now first coil that RSR uses is coil that player is in position for extra damage.
>[!CAUTION]
>Works only with new changes to RSR
> DreadCombo adjustment

- BasicRotations/Ranged/zMCH_Beta.cs
- BasicRotations/RebornRotations.csproj
> Use Reassemble on Spread/Scatter in low level AOE situations
