FFXIV-CombatReborn/RebornRotations

BasicRotations/Healer/SGE_Default.cs
While playing SGE, sometimes RSR just stops doing anything because of a crash:
After looking at the source, I found that we are checking the target of `EukrasianDiagnosisPvE` inside of `EukrasianPrognosisPvE`, which is the wrong spell. This leads to the "corrupted memory read" from the error message, because the target of `Diagnosis` might be an invalid reference now that we are casting `Prognosis`.
I guess that was a copy-paste mistake from the method just below, where `EukrasianDiagnosisPvE` is defined with similar code structure.
=> Fix wrong Prognosis target check

BasicRotations/Tank/PLD_Default.cs
this should do maybe, my thinking is by the time Blade of Honor is called one do not have Requiescat / Imperator remaining stacks
since Confiteor + 3 first blade would use it all
added a HasBoHReady but prolly not needed as per the base rotation
=> BoH out of requiescat  combo

BasicRotations/Healer/AST_Default.cs
//LordoC 7444 and LadyoC 7445
if ((MinorArcanaPvE.AdjustedID == 7444) || (MinorArcanaPvE.AdjustedID == 7445))
{
if ((MinorArcanaPvE.AdjustedID != 37022) && MinorArcanaPvE.CanUse(out act, usedUp: true)) return true;
};
//Umbral Draw
if ((AstralDrawPvE.AdjustedID == 37018) && (AstralDrawPvE.CanUse(out act))) return true;
//Astral Draw
if ((AstralDrawPvE.AdjustedID == 37017) && (AstralDrawPvE.CanUse(out act))) return true;
//Play1 37019 Orig - Play2 37020 Orig - Play3 37021 Orig
//Play1 37023 Balance - Play2 37024 Arrow - Play3 37025 Spear
//Play1 37026 Spear - Play2 37027 Bole - Play3 37028 Ewer
if (PlayIPvE.AdjustedID != 37019)
{
if (InCombat && PlayIPvE.CanUse(out act)) return true;
}
if (PlayIiPvE.AdjustedID != 37020)
{
if (InCombat && PlayIiPvE.CanUse(out act)) return true;
}
if …
=> worked out AST without gauge through adjustedID

BasicRotations/Magical/PCT_Default.cs
The PCT rotation gets stuck after level 90 because of the new spell Comet in Black. It has to be casted before using Holy in White, or else RSR gets stuck trying to cast Holy in White.
=> Fix PCT getting stuck above level 90

BasicRotations/Tank/PLD_Default.cs
noticed in MtGulg that it would keep spamming confiteor under requiescat after it was used once
so i added a stack check for requiescat so that it would only call it when theres 4 stacks of requiescat hence stopping the spam and correctly using holy circle / spirit
however after that fix i noticed that once again for lvl90+ it wasn't using the blade combo, after some checks i've came to understand it doesnt use the blade skills but was only spamming confiteor, so i added another stack check specifically for lvl90+
fixes https://github.com/FFXIV-CombatReborn/RebornRotations/issues/53
fixes https://github.com/FFXIV-CombatReborn/RebornRotations/issues/49
=> PLD80-89 fix

BasicRotations/Tank/WAR_Default.cs
• Prevent Onslaught clipping with auto heal defensives (might add same lines for Upheaval later, but so far in testing its somehow only a onslaught issue, prolly due to longer animation lock?)
• Onslaught range back to default RSR Value
• Removed my initial Status check which delayed Ruination by roughly 15 seconds bc the opener on release was still a placeholder. Ruination in opener is a big dps increase due to raid buffs which is kinda obvious.
=> Optimized warrior rotation. Perfection.

BasicRotations/Melee/MNK_Default.cs
Default Monk rotation updated with new Monk base rotation and skills. Rotation Solver Reborn needs the new Monk Base rotation pushed first before this can be used. Also this rotation hasn't been optimized.
=> Update MNK Default Rotation

BasicRotations/Tank/GNB_Default.cs
Fixed Burst strike AOE Check
Fixed Ammo Overcap on all levels
No Mercy window GCDs are *Perfect*
=> Fixed Gnashing Fang not executing 100% of the time

BasicRotations/Melee/DRG_Default.cs
Dragoon GCD ordered correctly, checks for Wyrmwind to be used when under damage buff or before overcap, Lifesurge check to ensure good damage potency
=> Dragood fix and optimization pass

BasicRotations/Magical/RDM_Default.cs
Fixed melee AOE, now get used properly.
Added additional config for use manafication outside of embolden window (ONLY IN MELEE).
Added additional logic to acceleration/swiftcast usage on move, they will not overwrite each other anymore.
After each acceleration grand impact will be used.
Added aditional logic to reprise usage, now rotation prioritize ANYTHING (acceleartion/swiftcast/any spells that can be instacasted) instead of reprise, also, added check if player have 50/50 mana - reprise not will be used to not break ready melee combo.
=> RDM additional logic / Fix for AOE melee combo

BasicRotations/Melee/RPR_Default.cs
Current version has RPR still on Api 2, so it doesn't show up ingame.
=> Api3 for RPR

BasicRotations/Melee/MNK_Default.cs
MNK has been fully updated to run automatically all the way with a DK opening and restrictively ordered rotation. 
Known issue: If you die during the fight, a lot of cooldowns won't connect as they were designed to. Feel free to weave PB, BH etc by yourself. 
It's been tested on level 100 dummy, ex 1 (85 parse) and ex 2 (79 parse). Note: I don't have week 1-2 normal raid tokens for MNK and I'm using SAM-compatible gear. It's also been tested in dungeons (AOE only with duty support, not full run) on level 100, 91, 90, 81, 80 and 59.
Additional features: Added two user options - PB logics can be turned on (default) or off per user preference. No more endless form shifting etc.
=> MNK full auto

BasicRotations/Melee/NIN_Default.cs
Huton is no longer required in the prepull since it's usage has changed to an attack. This would cause very early pulls
=> NIN - Removing Huton from Prepull

BasicRotations/Magical/PCT_Default.cs, BasicRotations/Magical/RDM_Default.cs, BasicRotations/Melee/DRG_Default.cs, BasicRotations/Melee/NIN_Default.cs, BasicRotations/Melee/VPR_Default.cs, BasicRotations/Ranged/BRD_Default.cs, BasicRotations/RebornRotations.csproj
PCT: now uses mits
RDM: you can now do more than use vercure in rotation config 4 times
DRG: aoe rotation restored, dungeon runners rejoice
NIN: Removed Huton from prepull
VPR: added configs and internal logic, now allows you to set how many stacks of Uncoiled Fury you want to use up while in melee out of burst, if in a 2 minute burst window will use all stacks regardless
BRD: hella optimization, now pools bloodletter stacks better and keeps from overcapping due to Mage song
=> PCT, RDM, DRG, VPR, and BRD fixes

BasicRotations/Melee/NIN_Default.cs
My bad about not testing it! Definitely tested this time and fixed the build
During the testing, I noticed an inefficacy around Armour Crush vs Aeolian Edge. Probably still not optimal, but at least it's not overcapping now
I also noticed that Tenri Jindo was never being used, not the best usage of it, but it at least gets used, and seems to not drift out of raid buffs. The fact it gets used is a big improvement though
=> NIN - Fix broken build + added Tenri Jindo

BasicRotations/Healer/SCH_Default.cs
They were using the unassignable action, so this update just fixes the action to be the correct one.
=> Fix Fey Illumination and Whispering Dawn

BasicRotations/Tank/PLD_Alpha.cs
Main Features: The ability to adjust beginning of the burst window. Option to prioritize the Atonement combo before Confiteor combo so uptime isn't lost if player dips outside of melee range, and something similar for Holy Spirit making it used last in priority  so it's used when outside of melee range. Some conditionals could potentially be redundant due to attempts to minimize edge cases, but I've tried to minimize it. Added as an Alpha since it's been modified quite a bit I think.
=> Edited the Default PLD Rotation and added customizablity and more consistant DPS during FoF windows

BasicRotations/Duty/VariantDefault.cs, BasicRotations/Healer/AST_Default.cs, BasicRotations/Healer/WHM_Default.cs, BasicRotations/Melee/VPR_Default.cs, BasicRotations/RebornRotations.csproj
Updated `VariantDefault`, `AST_Default`, `WHM_Default`, and `VPR_Default` classes.
Key changes include:
- `VariantDefault.cs`: Added `skipStatusProvideCheck` parameter to fix issue not being used.
- `AST_Default.cs`: Added `BubbleProtec` config, and adjusted defensive logic methods, potential fix for Oracle, Microcosmos and Collective whatever the fuck its called.
- `WHM_Default.cs`: Modified `DefenseAreaAbility` and `HealAreaAbility` methods, potential fix for Divine Caress.
- `VPR_Default.cs`: Added `ReawakenDelayTimer` config`.
- `RebornRotations.csproj`: nuget bump
=> Round of fixes

BasicRotations/Healer/AST_Default.cs, BasicRotations/Melee/VPR_Default.cs
Added a new `MicroPrio` configuration to `AST_Default` to prioritize `Microcosmos` over other healing actions. Updated several methods in `AST_Default` to respect `MicroPrio` and `Macrocosmos` status, preventing other actions when active. Modified `VPR_Default` to allow specific AOE abilities to bypass AOE checks with `skipAoeCheck: true`.
=> Add MicroPrio option and update AOE ability checks

BasicRotations/Healer/AST_Default.cs, BasicRotations/Magical/ICWA_PCT_BETA.cs, BasicRotations/Magical/SMN_Default.cs, BasicRotations/Melee/NIN_Default.cs, BasicRotations/Melee/VPR_Default.cs, BasicRotations/Ranged/BRD_Default.cs, BasicRotations/Tank/zPLD_Alpha.cs
add skips for later steps of aoe rotation to prevent bricking if enemy totals drop below AOE threshold
=> VPR AOE fixes and formatting fixes

BasicRotations/Melee/VPR_Default.cs, BasicRotations/Ranged/BRD_Default.cs
Refactored status checks in `VPR_Default.cs` by replacing `StatusID.Reawakened` with `StatusID.ReadyToReawaken` in multiple conditionals, affecting abilities like `UncoiledFuryPvE` and `SerpentsIrePvE`.
Expanded `InBurstStatus` logic in `BRD_Default.cs` to include additional conditions based on player level and status effects such as `BattleVoice` and `RadiantFinale`, making the burst status check more comprehensive.
Removed BRD Experemental pot usage.
Updated logic for using `RadiantFinalePvE` and `BattleVoicePvE` in `BRD_Default.cs` to include more detailed conditions considering cooldowns and player status effects.
Modified the `GeneralGCD` method in `BRD_Default.cs` to check for the `BattleVoice` status instead of `RagingStrikes` when determining if `IronJawsPvE` should be used.
=> Refactor status checks and ability logic in VPR and BRD

BasicRotations/Magical/SMN_Default.cs, BasicRotations/Melee/RPR_Default.cs, BasicRotations/Melee/VPR_Default.cs, BasicRotations/Ranged/MCH_Default.cs, BasicRotations/Tank/PLD_Default.cs, BasicRotations/Tank/WAR_Default.cs
Removed out of countdown automatic pot usage from all but DNC, added pot usage toggle to VPR as an experiment
=> Pot usage removal

BasicRotations/Ranged/zDNC_Beta.cs
Now RSR should use FanDance II instead of FanDance when near 2+ targets
=> Dancer FanDance Aoe Fix

BasicRotations/Melee/VPR_Default.cs, BasicRotations/RebornRotations.csproj
The `VPR_Default` class has been enhanced with new methods:
- Modified cooldown for `SerpentsIrePvE` from 85 to 115 seconds.
- Added `HealSingleAbility` to check `SecondWindPvE` or `BloodbathPvE` usage.
- Added `AntiKnockbackAbility` to check `ArmsLengthPvE` usage.
- Added `InterruptAbility` to check `LegSweepPvE` usage.
Nuget Bump
=> Update VPR_Default methods and package version

BasicRotations/Healer/AST_Default.cs, BasicRotations/Healer/SCH_Default.cs, BasicRotations/Healer/SGE_Default.cs, BasicRotations/Healer/WHM_Default.cs, BasicRotations/Ranged/BRD_Default.cs, BasicRotations/RebornRotations.csproj
Introduced SwiftLogic to healer rotations to restrict Swiftcast usage to Raise only. Modified relevant methods to check for SwiftLogic and HasSwift status. Added BuffAlignment option to Bard rotation for better buff timing control. Updated RotationSolverReborn.Basic package to version 7.0.5.62. Included missing using directive in SGE_Default.cs and improved status checks and action conditions to allow for dismissing Eurkrasia when no longer needed.
=> SGE Eurkrasia improvements, BRD buff timing fix, healer swiftcast ghosting fix #1678

BasicRotations/Healer/AST_Default.cs, BasicRotations/Healer/SCH_Default.cs, BasicRotations/Healer/SGE_Default.cs, BasicRotations/Healer/WHM_Default.cs, BasicRotations/Melee/NIN_Default.cs, BasicRotations/Ranged/BRD_Default.cs, BasicRotations/RebornRotations.csproj, BasicRotations/Tank/zPLD_Alpha.cs
Modified AST, SCH, SGE, and WHM classes to include additional checks for specific PvE abilities in various GCD methods. Removed unused `using` directive in `SGE_Default.cs`. Removed `DisplayStatus` method from `NIN_Default.cs`. Updated `BRD_Default.cs` to add conditions for `BattleVoicePvE` usage. Refactored `DefenseAreaAbility` and `DefenseSingleAbility` methods in `zPLD_Alpha.cs`.
=> Healer stuff

BasicRotations/Healer/SGE_Default.cs
- Moved `#endregion` directive to a different location.
- Modified `if` conditions to include `InCombat` check for the following to prevent removal of buff out of combat:
- `DiagnosisPvE.CanUse`
- `EukrasianDyskrasiaPvE.Target.Target?.WillStatusEnd`
- `EukrasianDosisPvE.Target.Target?.WillStatusEnd`
=> SGE Eurkrasia out of combat fix

BasicRotations/RebornRotations.csproj, BasicRotations/Tank/WAR_Default.cs
Updated RebornRotations.csproj to change the version of the RotationSolverReborn.Basic package from 7.0.5.63 to 7.0.5.65.
Added a new configuration property PrimalRendDistance in WAR_Default.cs, allowing the maximum distance for using the Primal Rend ability to be set between 1 and 20 yalms.
Modified the logic for using the Primal Rend ability to utilize the new PrimalRendDistance property instead of a hardcoded value of 2 yalms.
=> Update package version and add PrimalRendDistance config

BasicRotations/Melee/DRG_Default.cs, BasicRotations/RebornRotations.csproj
Modified `StardiverPvE.CanUse` in `DRG_Default` to include an additional `isFirstAbility` parameter set to `true`. Updated `RebornRotations.csproj` to change `RotationSolverReborn.Basic` package version from `7.0.5.74` to `7.0.5.78`.
=> Update method call and package version

BasicRotations/Ranged/DNC_Default.cs
Won't use abilities right before dancing or while dancing because their animation lock might delay the dance, happened to me with curing waltz.
Sometimes it used FanDance II or FanDance when FanDance III was available, now it shouldn't.
However it's hard to test since it happens rarely, but i didn't notice a single instance of it happening for 2 hours so its probably working as intented now.
The anti overcapping mechanic for feathers now uses feathers before nextGCD that can generate it, instead of instantly when it hits 4, also moved the storing feathers mechanic to when the player hits level high enough for devilment instead of tech step.
It seems that the code that prevents using standard step when it would delay tech step didn't work properly. Fixed that
Tested on Dancer Lv 72 and 60. …
=> Dancer Optimalizations

BasicRotations/Ranged/MCH_Default.cs
According to the balance this should be 8-10 seconds not 6, Hypercharge takes 7.5~ seconds. Should reduce drifting chance.
=> Tool Hypercharge Drifting Fix

BasicRotations/Healer/SGE_Default.cs, BasicRotations/Magical/PCT_Default.cs, BasicRotations/Melee/DRG_Default.cs, BasicRotations/Melee/SAM_Default.cs, BasicRotations/Ranged/BRD_Default.cs, BasicRotations/RebornRotations.csproj, BasicRotations/Tank/WAR_Default.cs
- SGE_Default: Added level check for EukrasianDyskrasiaPvE and removed redundant status checks.
- PCT_Default: Added CountdownBuffer constant, simplified conditions, and refactored EmergencyAbility method.
- DRG_Default: Added OGCDTimers config, and modified StardiverPvE usage.
- SAM_Default: Simplified and fixed HiganbanaPvE logic.
- BRD_Default: Added OGCDTimers config and updated conditions for cooldown management.
- RebornRotations.csproj: Updated RotationSolverReborn.Basic package to 7.0.5.80.
- WAR_Default: Added YEET config for Primal Rend usage while moving and updated logic.
=> Update various classes and configurations

BasicRotations/Ranged/MCH_Default.cs, BasicRotations/RebornRotations.csproj
Updated `MCH_Default.cs` to refine ability selection logic:
- Check `HotShotMasteryTrait.EnoughLevel` before using `AirAnchorPvE`.
- Moved `HotShotPvE` condition to a later point if `AirAnchorPvE` is insufficient.
Updated `RebornRotations.csproj` to use `RotationSolverReborn.Basic` version `7.0.5.88`.
=> Update ability logic and package version

BasicRotations/Ranged/DNC_Default.cs
=> Added ability to specify dance partner

BasicRotations/Healer/AST_Default.cs, BasicRotations/RebornRotations.csproj
Enhanced the `AttackAbility` method in `AST_Default.cs` to include conditions that ensure `Lightspeed` status is not active before using `LightspeedPvE`. This prevents unnecessary usage of the `LightspeedPvE` ability when the `Lightspeed` status is already applied to the player.
=> Add checks to prevent redundant LightspeedPvE usage

BasicRotations/Ranged/zMCH_Beta_2.cs, BasicRotations/RebornRotations.csproj
=> MCH rework part 2 - the drillening

BasicRotations/Melee/RPR_Default.cs, BasicRotations/Melee/SAM_Default.cs, BasicRotations/RebornRotations.csproj
- Discovered that method `CanHitPositional` is unstable when used before `CanUse`, is that because `IBaseAction.Target.Target` changes only after `CanUse`?
- Updated Package in Dependencies
- Refactored code for clarity
=> Added positional feature to SAM and adjusted RPR

BasicRotations/Tank/DRK_Default.cs
(deprioritize Disesteem so no GCDs between combo)
Note: This will not work until https://github.com/FFXIV-CombatReborn/RotationSolverReborn/pull/427 is live
=> Handle scarlet delirium combo via IsLastGCD

BasicRotations/Healer/WHM_Default.cs
Previous behavior was to always reserve the last charge. This makes the behavior configurable and makes the default to reserve the last charge for raise.
=> Add configuration to control usage of the last thin air charge

BasicRotations/Melee/SAM_Default.cs
Based on the recent RSR pull, update Guren so it can be used for all levels. I don't know if anyone was still using this, but I got you if you were out there.
*Who updated SAM rotation after me? Who use bana asap in opener? This is SAM default not SAM UWU... Sigh*
=> Update Guren for all level use

BasicRotations/PVPRotations/Healer/AST_Default.PVP.cs, BasicRotations/PVPRotations/Healer/SCH_Default.PVP.cs, BasicRotations/PVPRotations/Magical/BLM_Default.PVP.cs, BasicRotations/PVPRotations/Magical/RDM_Default.PvP.cs, BasicRotations/PVPRotations/Magical/SMN_Default.PVP.cs, BasicRotations/PVPRotations/Melee/MNK_Default.PVP.cs, BasicRotations/PVPRotations/Melee/RPR_Default.PVP.cs, BasicRotations/PVPRotations/Melee/VPR_Default.PVP.cs, BasicRotations/PVPRotations/Ranged/BRD_Default.PVP.cs, BasicRotations/PVPRotations/Tank/DRK_Default.PVP.cs, BasicRotations/PVPRotations/Tank/PLD_Default.PVP.cs, BasicRotations/Ranged/BRD_Default.cs, BasicRotations/RebornRotations.csproj
Updated various PvP classes to remove outdated checks and actions, and added new abilities and checks. Key changes include:
- `AST_DefaultPVP`: Removed `TheBolePvP`, `TheArrowPvP`, `TheBalancePvP`; added `MoveForwardAbility`, `OraclePvP`, `LordOfCrownsPvP`, `MinorArcanaPvP`, `LadyOfCrownsPvE`.
- `SCH_DefaultPVP`: Removed `MummificationPvP`.
- `BLM_DefaultPVP`: Removed `NightWingPvP`, `SuperflarePvP`.
- `RDM_DefaultPvP`: Removed `MagickBarrierPvP`, `FrazzlePvP`, `WhiteShift`, `BlackShift`; added `FortePvP`, `PrefulgencePvP`, `EmboldenPvP`, `JoltIiiPvP`, `GrandImpactPvP`, `ScorchPvP`.
- `SMN_DefaultPvP`: Removed `FesterPvP`, `EnkindleBahamutPvP`, `EnkindlePhoenixPvP`.
- `MNK_DefaultPvP`: Moved `GeneralGCD` to `AttackAbility`; added `EarthsReplyPvP`, `WindsReplyPvP`, `FiresReplyPvP`, …
=> Update PvP classes and upgrade RotationSolverReborn

BasicRotations/PVPRotations/Ranged/BRD_Default.PVP.cs
Updated GameVersion in Rotation annotation from "7.05" to "7.1". Reordered ability checks in AttackAbility method:
- Moved SilentNocturnePvP after EncoreOfLightPvP and HarmonicArrowPvP_41964.
- Added EncoreOfLightPvP with skipAoeCheck set to true. Added a check for HarmonicArrowPvP_41964 before BlastArrowPvP.
=> Update GameVersion and modify ability checks order

BasicRotations/Healer/AST_Default.cs
Earthly Star did not want to cast pre-pull. This fixes it.
=> Fix Pre-pull Earthly star for Astrologian
